refactor: handle legacy(kmods) and main(nokmods) builds and naming

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,8 +28,8 @@ jobs:
           - lxqt
           - mate
           - vauxite
-        image_flavor: [main, nokmods]
         major_version: [37, 38, 39]
+        build_target: [main, legacy]
         include:
           - major_version: 37
             is_latest_version: false
@@ -44,9 +44,6 @@ jobs:
             is_stable_version: false
             is_gts_version: false
         exclude:
-          # Fedora 39 images do not include kmods
-          - image_flavor: nokmods
-            major_version: 39
           # There is no Fedora 37 version of sericea
           - image_name: sericea
             major_version: 37
@@ -57,6 +54,11 @@ jobs:
             major_version: 38
           - image_name: vauxite
             major_version: 39
+          # THE FOLLOWING EXCLUDE IS MESSY BUT TEMPORARY UNTIL F38 IS GONE
+          # see: https://github.com/ublue-os/main/issues/369
+          # Fedora 39+ images do not include custom kmods (legacy)
+          - build_target: legacy
+            major_version: 39
     steps:
       - name: Maximize build space
         uses: ublue-os/remove-unwanted-software@v6
@@ -66,13 +68,27 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Matrix Variables
+        shell: bash
         run: |
-          echo "IMAGE_NAME=${{ matrix.image_name }}-${{ matrix.image_flavor }}" >> $GITHUB_ENV
           if [[ "${{ matrix.image_name }}" == "lxqt" || "${{ matrix.image_name }}" == "mate" ]]; then
               echo "SOURCE_IMAGE=base" >> $GITHUB_ENV
           else
               echo "SOURCE_IMAGE=${{ matrix.image_name }}" >> $GITHUB_ENV
           fi
+          # THE FOLLOWING IS MESSY BUT TEMPORARY UNTIL F38 IS GONE
+          # see: https://github.com/ublue-os/main/issues/369
+          # Fedora 39+ images do not include custom kmods (legacy)
+          if [[ "${{ matrix.major_version}}" -ge "39" && "${{ matrix.build_target }}" == "main" ]]; then
+              export IMAGE_FLAVOR=main
+          elif [[ "${{ matrix.major_version}}" -lt "39" && "${{ matrix.build_target }}" == "main" ]]; then
+              export IMAGE_FLAVOR=nokmods
+          elif [[ "${{ matrix.major_version}}" -lt "39" && "${{ matrix.build_target }}" == "legacy" ]]; then
+              export IMAGE_FLAVOR=main
+          else
+              echo "ERROR: invalid workflow request - ${{ matrix.major_version }} - ${{ matrix.build_target }}"
+              exit 1
+          fi
+          echo "IMAGE_NAME=${{ matrix.image_name }}-${IMAGE_FLAVOR}" >> $GITHUB_ENV
 
       - name: Generate tags
         id: generate-tags
@@ -161,13 +177,12 @@ jobs:
             ${{ steps.generate-tags.outputs.alias_tags }}
           build-args: |
             IMAGE_NAME=${{ matrix.image_name }}
-            IMAGE_FLAVOR=${{ matrix.image_flavor }}
             SOURCE_IMAGE=${{ env.SOURCE_IMAGE }}
             FEDORA_MAJOR_VERSION=${{ matrix.major_version }}
           labels: ${{ steps.meta-main.outputs.labels }}
           oci: false
           extra-args: |
-            --target=${{ matrix.image_flavor }}
+            --target=${{ matrix.build_target }}
 
       # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
       # https://github.com/macbre/push-to-ghcr/issues/12
