chore(nvidia): moving nvidia builds from hwe to main (#813)

diff --git a/.github/workflows/reusable-build.yml b/.github/workflows/reusable-build.yml
--- a/.github/workflows/reusable-build.yml
+++ b/.github/workflows/reusable-build.yml
@@ -10,6 +10,11 @@ on:
         description: The name of the image to build.  E.G. base, silverblue
         required: true
         type: string
+      image_variant:
+        description: The variant of image to build.  E.G. main, nvidia
+        required: false
+        type: string
+        default: "main"
       source_image_name:
         description: The name of the image to use as a source.  E.G. sway-atomic
         required: false
@@ -44,7 +49,7 @@ jobs:
           fi
 
           echo "SOURCE_ORG=fedora-ostree-desktops" >> $GITHUB_ENV
-          echo "IMAGE_NAME=$IMAGE_NAME-main" >> $GITHUB_ENV
+          echo "IMAGE_NAME=$IMAGE_NAME-${{ inputs.image_variant }}" >> $GITHUB_ENV
           echo "SOURCE_IMAGE=$SOURCE_IMAGE" >> $GITHUB_ENV
 
       - name: Generate tags
@@ -136,12 +141,19 @@ jobs:
             exit 1
           fi
 
+          AKMODS_NVIDIA_DIGEST=$(yq -r ".images[] | select(.name == \"akmods-nvidia-open-${VERSION}\") | .digest" "$IMAGE_VERSIONS_FILE")
+          if [ -z "$AKMODS_NVIDIA_DIGEST" ]; then
+            echo "AKMODS_NVIDIA_DIGEST not found in image-versions.yaml"
+            exit 1
+          fi
+
           BASE_IMAGE_DIGEST=$(yq -r ".images[] | select(.name == \"${SOURCE_IMAGE}-${VERSION}\") | .digest" "$IMAGE_VERSIONS_FILE")
           if [ -z "$BASE_IMAGE_DIGEST" ]; then
             echo "BASE_IMAGE_DIGEST not found in image-versions.yaml"
             exit 1
           fi
           echo "AKMODS_DIGEST=${AKMODS_DIGEST}" >> $GITHUB_OUTPUT
+          echo "AKMODS_NVIDIA_DIGEST=${AKMODS_NVIDIA_DIGEST}" >> $GITHUB_OUTPUT
           echo "BASE_IMAGE_DIGEST=${BASE_IMAGE_DIGEST}" >> $GITHUB_OUTPUT
 
       - name: Get current version
@@ -206,6 +218,7 @@ jobs:
             IMAGE_REGISTRY=${{ env.IMAGE_REGISTRY }}
             BASE_IMAGE_DIGEST=${{ steps.query-digest.outputs.BASE_IMAGE_DIGEST }}
             AKMODS_DIGEST=${{ steps.query-digest.outputs.AKMODS_DIGEST }}
+            BUILD_NVIDIA=${{ inputs.image_variant == 'nvidia' && 'Y' || 'N' }}
           labels: ${{ steps.meta.outputs.labels }}
           oci: false
 
